modLoader="javafml" #mandatory

loaderVersion="[28,)" #mandatory

#issueTrackerURL="http://my.issue.tracker/" #optional



[[mods]] 

modId="beastly_customization" 

version="7.1.0" 

displayName="Beastly Customization 1.14.4" 

#updateJSONURL="http://myurl.me/" #optional

#displayURL="http://example.com/" #optional

logoFile="CoverImg.png" #optional

credits="Me, cuz I am duh one dont weigh a ton, dont need a gun to get respect up on the streets."

authors="WGHxPERNAxBEAST"

description='''
This mod adds a variety of things to the game. It was developed for the MMP Live Server.
I hope you enjoy :)
'''


[[dependencies.beastly_customization]]
    modId="forge" #mandatory
    mandatory=true
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.beastly_customization]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"